---
apiVersion: v1
kind: Service
metadata:
  name: master-crawler
  namespace: crawler
  labels:
    app: master-crawler
spec:
  clusterIP: None
  ports:
  - port: 8000
    name: http
  selector:
    app: master-crawler
