apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: jenkins
data:
  compose-pipeline.dsl: |
    pipelineJob('compose-pipeline') {
        parameters {
          stringParam('CLONE', '', 'Url of a git repository for cloning (https)')
          stringParam('PATH', 'undefined', 'Path to the docker-compose file')
          stringParam('NAME', 'docker-compose.yml', 'Name of the docker-compose file')
          stringParam('ID', '', 'Grakn database ID')
          stringParam('RID', '', 'GitHub sha of docker-compose file')
        }

        logRotator {
          numToKeep(100)
        }

        definition {
            cps {
                script('''
    pipeline {
      agent {
        kubernetes {
          cloud 'kubernetes'
          defaultContainer 'docker'
          yaml """
    kind: Pod
    spec:
      containers:
        - name: docker
          image: docker:19.03.12-dind
          securityContext:
            privileged: true
        - name: conftest
          image: instrumenta/conftest:v0.21.0
          tty: true
          command: ['cat']
            """
          }
        }

        options {
          timeout(time: 30, unit: 'MINUTES')
          timestamps()
        }

        stages {
            stage('Install Docker-Compose') {
              steps {
                sh 'apk update && apk add docker-compose'
              }
            }
            stage('Git Checkout') {
                steps {
                  git poll: false, url: params.CLONE
                }
            }
            stage('Switch Directory') {
              when  {
                expression { return params.PATH != 'undefined' }
              }
              steps {
                dir params.PATH
              }
            }
            stage('Run Compose') {
                steps {
                  sh 'ls -lh'
                  sh "docker-compose -f ${params.NAME} up -d"
                }
            }
            stage('Check Healthy state') {
                steps {
                  sh 'docker ps'
                }
            }
            stage('Run conftest') {
                steps {
                  container('conftest') {
                    sh 'conftest --version'
                  }
                }
            }
            stage('Calculate final score') {
                steps {
                  sh 'echo "hallo"'
                }
            }
            stage('Send feedback') {
                steps {
                  sh 'echo "hallo"'
                }
            }
        }
    }
                  '''.stripIndent())
                sandbox()
            }
        }
    }
