apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: jenkins
data:
  startup-pipeline.dsl: |
    pipelineJob("Build compose pipeline for parameters") {
        description('parameters are needed')
        keepDependencies(false)
        disabled(false)
        triggers {
          hudsonStartupTrigger {
            nodeParameterName("master")
            label("master")
            quietPeriod("0")
            runOnChoice("False")
          }
        }
        
        definition {
          cps {
            script('''
    pipeline {
      agent any
      stages {
        stage('Trigger Job') {
          steps {
            build job: 'compose-pipeline'
          }
        }
      }
    }
    '''.stripIndent())
    sandbox()
          }
        }
      }
  compose-pipeline.dsl: |
    pipelineJob('compose-pipeline') {
        definition {
            cps {
                script('''
    pipeline {
      agent {
        kubernetes {
          cloud 'kubernetes'
          defaultContainer 'docker'
          yaml """
    kind: Pod
    spec:
      containers:
        - name: docker
          image: docker:19.03.12-dind
          securityContext:
            privileged: true
        - name: conftest
          image: instrumenta/conftest:v0.21.0
          tty: true
          command: ['cat']
            """
          }
        }

        options {
          timeout(time: 30, unit: 'MINUTES')
          timestamps()
          buildDiscarder(logRotator(numToKeepStr: '1'))
        }

        parameters {
          string(name: 'CLONE', defaultValue: '', description: 'Url of a git repository for cloning (https)')
          string(name: 'PATH', defaultValue: 'undefined', description: 'Path to the docker-compose file')
          string(name: 'NAME', defaultValue: 'docker-compose.yml', description: 'Name of the docker-compose file')
          string(name: 'ID', defaultValue: '', description: 'Grakn database ID')
          string(name: 'RID', defaultValue: '', description: 'GitHub sha of docker-compose file')
        }

        stages {
            stage('Install Docker-Compose') {
              steps {
                sh 'apk update && apk add docker-compose'
              }
            }
            stage('Git Checkout') {
                steps {
                  git poll: false, url: params.REPOSITORY
                }
            }
            stage('Switch Directory') {
              when  {
                expression { return params.COMPOSE_PATH != 'undefined' }
              }
              steps {
                dir params.COMPOSE_PATH
              }
            }
            stage('Run Compose') {
                steps {
                  sh 'ls -lh'
                  sh "docker-compose -f ${params.COMPOSE_FILENAME} up -d"
                }
            }
            stage('Check Healthy state') {
                steps {
                  sh 'docker ps'
                }
            }
            stage('Run conftest') {
                steps {
                  container('conftest') {
                    sh 'conftest --version'
                  }
                }
            }
            stage('Calculate final score') {
                steps {
                  sh 'echo "hallo"'
                }
            }
            stage('Send feedback') {
                steps {
                  sh 'echo "hallo"'
                }
            }
        }
    }
                  '''.stripIndent())
                sandbox()
            }
        }
    }
