jenkins:
  systemMessage: |
    Jenkins configured automatically by Jenkins Configuration as Code Plugin
  authorizationStrategy: unsecured
  numExecutors: 0
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  remotingSecurity:
    enabled: false
  clouds:
  - docker:
      name: "docker"
      dockerApi:
        dockerHost:
          uri: "unix:///var/run/docker.sock"
      containerCap: 0
      exposeDockerHost: true
      templates:
        - labelString: "docker-agent"
          dockerTemplateBase:
            image: "jenkins/slave"
          remoteFs: "/home/jenkins/agent"
          connector:
            attach:
              user: "jenkins"
          instanceCapStr: "10"
          retentionStrategy:
            idleMinutes: 1
unclassified:
  location:
    url: "${JENKINS_HOST}"
tool:
  git:
    installations:
      - name: git
        home: /bin/git
