version: '3'

services:
  jenkins:
    build:
      context: .
    ports:
      - 9080:8080
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_casc.yml
      JENKINS_HOST: http://localhost:9080
    volumes:
      - $HOME/data:/var/jenkins_home
      - ./config.yml:/var/jenkins_casc.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
