---
apiVersion: v1
kind: Service
metadata:
  name: recommender
  namespace: frontend
  labels:
    app: recommender
spec:
  type: NodePort
  ports:
  - port: 8088
    name: http
    nodePort: 30808
  selector:
    app: recommender
